engines:
  csslint:
    enabled: true
    checks:
      fallback-colors:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 25
  markdownlint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true

ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.md"

exclude_paths:
- "spec/app/**/*"
