language: node_js

sudo: false

node_js:
  - "6"

cache:
  directories:
    - client/node_modules

addons:
  code_climate:
    repo_token: 4ad3e12283a16e2adf2b673cf3c3d3fd211af822b86105bd768136c72bf16eb1

script: flow

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
