language: node_js
sudo: false
node_js:
  - "6"
cache:
  directories:
    - client/node_modules
script: cd client && npm install && npm test -- --coverage
after_script:
    # killing background process
  - killall -9
