language: node_js
sudo: false
node_js:
  - "6"
cache:
  directories:
    - client/node_modules
script: cd client && npm install && npm test -- --coverage
after_script:
  # - ps aux
  - killall -9 php
  - killall -9 java
  - killall -9 Xvfb
  # - ps aux
